language: java
jdk: oraclejdk8
branches:
  only:
    - master
    - 3.0.0-SNAPSHOT
script: mvn clean install
notifications:
  slack:
    on_success: always
    on_failure: always 
  email:
    recipients:
      - demoiselle-users@lists.sourceforge.net
      - paulo.pinheiro@serpro.gov.br
      - vanderson.silva@serpro.gov.br
    on_success: always
    on_failure: always