language: java
jdk: oraclejdk8
branches:
  only:
    - master
    - 3.0.0-SNAPSHOT
script: 
    - mvn clean install -Pjacoco -Pcoveralls coveralls:report
notifications:
  slack:
    on_success: always
    on_failure: always 
  email:
    recipients:
      - demoiselle-devel@lists.sourceforge.net
    on_success: never
    on_failure: always
